tasks:
  - init: |
      # echo 'TODO: build project'
      npm install
    command: |
      # echo 'TODO: start app'
      npm run dev

ports:
  - port: 3000
    # visibility: private
    onOpen: open-browser