tasks:
  - init: |
      # echo 'TODO: build project'
      npm install
    command: |
      # echo 'TODO: start app'
      export HMR_HOST=`gp url 3000`
      npm run dev

ports:
  - port: 3000
    # visibility: private
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode